Feature/awesome books with es6
beteland123/Awesome-books-with-ES6 pull request #1
Opened 2023-05-09 16:53 UTC by beteland123

# Restructure the Awesome Books app code with ES6. 
- make it more organized by using modules. 
 -practice the ES6 syntax that I have learned.
-Divide my code into modules.
-Create a separate file for each module in the modules directory.
-Import modules into the index.js file. 
-Keep all functionalities of the app without errors.
-Refactor your functions to arrow functions.
-Use let and const in the correct way.
-Display the current date below the navigation bar. use a library [Luxon](https://moment.github.io/luxon/#/install?id=es6)

2023-05-09 18:31 UTC, pinkmoon25 requested changes
Hi @beteland123 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
Linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 
ES6 and modules :heavy_check_mark: 
Luxon :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 18:31 UTC, pinkmoon25 commented on modules/book.js
> +
- [ ] Good work using ES6 syntax and modules :clap:, while checking the application functionality I came across this issue when trying to remove a particular book from the list, I have recorded a small demo to show it clearly, so the book that I select to remove is not removed rather the book before it gets removed 

https://github.com/beteland123/Awesome-books-with-ES6/assets/97521557/0625a3fa-8d38-4fea-b7ae-393889d53e8f

I would suggest using a unique Id value for your books rather than using array length, as it can cause issue, you can use the uuid gem to generate a unique id it is pretty simple to use also, and then based on the id you can just filter the books array :+1:

2023-05-09 18:31 UTC, PinkMoon25 commented on index.js
> +// import {bookAdder} from './modules/addBook.js'
- [ ] As mentioned in the best practices we should avoid committing commented code to the codebase, I would suggest to remove this commented code from the codebase

2023-05-09 18:31 UTC, PinkMoon25 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] In order to make sure our Readme is professional, Please fix the broken MIT link in your Readme currently it is showing a 404 page not found error

2023-05-10 00:19 UTC, DuaneDave approved these changes
Hi @beteland123 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good job fixing the bug on the delete functionality
✔️ Readme is up to professional standards now

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 00:25 UTC, merged